version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - testifylint
    - unused
formatters:
  enable:
    - gofmt ./...
    - goimports --local user-account/ -l -w .